### ISSUE TITLE
Ensure that `tasks_loop` checks for multiple tasks

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#29]
As discussed in this morning's awesome demo, we have this section where it seems that there's an assumption that only one task will be discovered. See this comment about it:

https://github.com/CronCats/croncat-rs/pull/27/files#r969992853

**Comment by TrevorJTClarke** [comment]
Ah yes definitely.
Within a block, agent could get many tasks (say 20).
Would be awesome to be able to batch `proxy_call` so we dont have sequential execution.

**Comment by mikedotexe** [comment]
Looks like this is working right meow? @SeedyROM maybe you know 🙏
