### ISSUE TITLE
Remove stack trace from error

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#31]
Sometimes an error will be shown but we're seeing quite a bit of the stack trace.
Let's see if we can find a way to remove the stack trace so it's simpler.

<img width="1402" alt="Screen Shot 2022-09-14 at 8 54 44 PM" src="https://user-images.githubusercontent.com/1042667/190310468-97c751c2-ebb5-436c-9fb0-9d87a8694b6e.png">

**Comment by SeedyROM** [comment]
I intentionally setup `color_eyre` to print the entire stack trace:

https://github.com/CronCats/croncat-rs/blob/aa81f2a985c302f0fca4f738029137b83ab51b80/croncat/src/logging.rs#L16-L18

You can disable it by putting `RUST_LIB_BACKTRACE=0` before your `cargo run` or setting that env var. I don't think removing the stack trace is a good idea in general, so if you want a less cluttered output just change that env var.

**Comment by SeedyROM** [comment]
Another solution is to not set that environment variable when running in release mode, so the end users don't see the cluttered stack trace. But I'm not sure if that's why you want to remove it.

**Comment by SeedyROM** [comment]
@mikedotexe Thoughts?

**Comment by d3v3us** [comment]
Capturing a backtrace can be a quite expensive maybe we could keep it disabled by default?

**Comment by SeedyROM** [comment]
> Capturing a backtrace can be a quite expensive maybe we could keep it disabled by default?

Pretty sure crashing is expensive too, I don't see a reason besides hiding info about a crash.

**Comment by SeedyROM** [comment]
I also think rust always unwinds the stack on panic but simply doesn't show it. So I don't see a point.

**Comment by SeedyROM** [comment]
Ties to #79, but this issue has been resolved with a recent commit to main.

**Comment by SeedyROM** [comment]
Ties to #79 , but this issue has been resolved with a recent commit to main.
