### ISSUE TITLE
Change daemon command to set up service

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#32]
Currently, we have `go` and the `daemon` command that are doing similar tasks.

What we want to do is have the `daemon` command do everything necessary on the computer so that it becomes a "service." This will make sure it restarts if the power goes off and it reboots, and things like that.

Let's take a look at how the original, JavaScript daemon is working:
https://github.com/CronCats/croncat#croncat-agent-daemon

Luckily, we have this fairly short JavaScript file to reference:
https://github.com/CronCats/croncat/blob/ab1061bba23103f223d367da0932de93ccbe1432/src/createSystemctl.js

---

So when an end user types the command:

`croncatd daemon`

it will not begin the looping, waiting for tasks. instead, it will :v: install :v: all the system services files.

**Comment by mikedotexe** [comment]
Whoever takes this task may also find this interesting:
https://docs.junonetwork.io/validators/setting-up-cosmovisor#set-up-service

It's about setting up a service for your Juno node. Pretty neat.

**Comment by SeedyROM** [comment]
I'll take this one on as a warm up for getting back into the codebase.

**Comment by SeedyROM** [comment]
@mikedotexe @TrevorJTClarke In #39 do we need this to create `systemd` entries only? (aka most Linux based servers) or also for `launchd` (which is OSX's custom version of `systemd`).

Right now and in the script mentioned we only handle `systemd`.

**Comment by SeedyROM** [comment]
Woah sorry for the link spam, I clicked link and it went into a weird input loop.
