### ISSUE TITLE
Ensure `--chain-id` flag isn't required everywhere

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#50]
When I was trying to set up my agent just now I ran `generate-mnemonic` and wasn't allowed to because of the chain ID flag.

Feels like we should have this be optional for this command and commands like this.

The task is to make sure that only the commands that need the chain ID require it.

<img width="939" alt="Screen Shot 2022-09-22 at 12 45 07 PM" src="https://user-images.githubusercontent.com/1042667/191837456-063bb64c-92d0-495d-b143-728040952936.png">

**Comment by d3v3us** [comment]
On it for fixing)

**Comment by Buckram123** [comment]
Hey, should we store multiple account_addr's for one seed?
Thanks for reminding me about using `config.prefix` there, it's hardcoded "juno" rn 😞

**Comment by mikedotexe** [comment]
> Hey, should we store multiple account_addr's for one seed?

Not sure what you mean by this, can you give me an example?

**Comment by Buckram123** [comment]
> Not sure what you mean by this, can you give me an example?

I mean getting bech32 from the same seed phrase for other chains, currently it's hardcoded with the "juno" prefix, we can add helper command, example:
```bash
croncatd helpers get_addr --chain-id dogs --agent bob
```

![IMG_20220924_140318](https://user-images.githubusercontent.com/91957742/192094362-218257df-68d5-40ed-8422-d1ced13ff7c7.jpg)

**Comment by Buckram123** [comment]
And just don't store addr in agents.json, wdyt? @mikedotexe
