### ISSUE TITLE
Ensure that agent.json file allows for keys other than "agent"

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#55]
We ran into an issue where if you create a mnemonic for an account that's not called `agent` then it will break the workflow.
I believe `agent` is current the default, but you can specify another name.

Trevor ran into this problem and we realized he needed to manually modify his `~/.croncatd/agents.json` file, changing "purr" to "agent" and then things started working.

Let's make sure we can have different names available, please. (Or if this becomes complicated, we can talk through other options.)

**Comment by d3v3us** [comment]
Yes, different names available, for each agent different LocalAgentStorageEntry is used for signing.
