### ISSUE TITLE
[RFC]: We currently have no license, what's the plan?

### ISSUE THREAD

**Issue by SeedyROM** [SeedyROM/croncat-rs#62]
So right now we have no license for this project, Are we going to follow in the footsteps of [cw-croncat](https://github.com/CronCats/cw-croncat) and use Apache 2.0?

@TrevorJTClarke @mikedotexe Thoughts?

**Comment by TrevorJTClarke** [comment]
@SeedyROM good call -- lets roll with https://github.com/CronCats/catgrass-ui/blob/main/LICENSE
