### ISSUE TITLE
[RFC]: Discuss Stream Handler Logging

### ISSUE THREAD

**Issue by SeedyROM** [SeedyROM/croncat-rs#65]
Currently we log most things to `info`, that's great for us developing stuff. But for the end user, should they see every minutia of processes running? 

Should we move all the info logs from each stream module to `trace` and intentionally print to `stdout` for specific things. Such as tasks running, no tasks to be processed at the current block etc.

@TrevorJTClarke @mikedotexe @Buckram123 @deveusss 

Open to ideas!

**Comment by d3v3us** [comment]
I would bet for structured tokio tracing, with some context and time intervals

**Comment by TrevorJTClarke** [comment]
Great discussion!!

Here's my wants/needs:
* Agent runners (people that run agents) important info: [NEED]
  * Here's the previous ongoing log (yes its a mess): https://github.com/CronCats/croncat/blob/main/src/tasks.js#L25-L26
  * Startup should show what wallet, network, agent status, agent native token balance, agent reward balance, timestamp
  * Schedule loop: (triggered every block) timestamp, Agent status, agent nickname ("agent"), network ("juno-1"), agent block & timestamp task count (from agent get-tasks)
  * Event loop: (Triggered when query eval's to TRUE) timestamp, agent nickname ("agent"), network ("juno-1"), task hash
* Stats: [WANT]
  * Avg tasks completed total per day
  * Avg tasks failed total per day
  * Reward balance
  * stats could either be behind a CLI command, or periodically report.
  * stats should require any kind of crazy DB, just could use in memory, and if agent crashes just start new
  * could log every 1hr or something
* Debugging: [WANT]
  * For agents that turn on debugging so we can find crashes, turned on via flag OR it just generates trace to a different log file in case of epic failures, so we actually capture something.
  * Verbose flag, so we can hide too much info from agent logs

Lastly - consider log rotation: We want agents to be light weight, and if a disk gets full and crashes the OS, thats def not what we want. I would think keeping 1 day of history could be ideal here.

**Comment by SeedyROM** [comment]
I think we can have local task remove longer than day old log files! It would be simple to add to the global system.
