### ISSUE TITLE
Add RPC that Agent can connect to

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#71]
While using public RPC endpoints will work for now, we'd like to work towards having the CronCat Agent talk to an RPC node that's set up for itself.

You can see an example of a `wasmd` Docker image getting started up here:
https://github.com/CronCats/launch-tools/blob/239f812055b7b3aec86d780a84bb3c76a87df04d/start.sh#L24-L33

(Since `wasmd` hasn't been updated in a while, and CronCat might use more modules, it's recommended to use `junod` instead, which can be [found here](https://github.com/CosmosContracts/juno).)

There's also the idea of having this as a `pkg`, which I might need for more on @TrevorJTClarke, but here's a link that I believe may be helpful if we're discussing publishing this as a 'Nix package.
https://linuxconfig.org/easy-way-to-create-a-debian-package-and-local-package-repository

**Comment by SeedyROM** [comment]
See reply on discord about my confusion on this.

**Comment by TrevorJTClarke** [comment]
hey @SeedyROM -- is this solved by the recent updates to multi-config?
Or do we now need another config for adding your own provider into the list?

**Comment by SeedyROM** [comment]
This and the balance withdrawal from the contract are on my list next! With our current config we only use the chain registry.
