### ISSUE TITLE
Registering agent throws an error when successful

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#72]
This ticket is to investigate and fix the issue where an agent registers, but an error is thrown to the end user.
Upon inspection, however, it seems that it has succeeded. This may involve understanding some of the smart contract code as well. A likely place in the smart contract is:

https://github.com/CronCats/cw-croncat/blob/b9ce3969dcba580cea33e66c48a1115e3f10e53f/contracts/cw-croncat/src/agent.rs#L119-L207

Can reproduce by having the contract deployed, config set, and in the `croncat-rs` repo executing:

    cargo run register-agent

**Comment by SeedyROM** [comment]
What is the error you're seeing locally?

**Comment by TrevorJTClarke** [comment]
Closing this, as after the recent update to error handling, this is no longer happening.
Register executes and closes as expected now.
