### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#73]
This will likely be somewhat of an ongoing effort, but let's set up some continuous integration / continuous deployment.

There are some ways we can start, where we run tests on GitHub pull requests and whatnot. You can reference the files here:
https://github.com/CronCats/cw-croncat/tree/main/.github/workflows

It's possible we can set up some more complex Dockerized environments that could actually set up a local `junod` node, and run through the entire process of having an agent register and fulfill a task.

Let's make a good first effort for this ticket and be sure to create another ticket for items that we'd like to incrementally improve on the CI/CD front.

**Comment by SeedyROM** [comment]
I like this idea!
