### ISSUE TITLE
[FEATURE]: Multi-location file logging.

### ISSUE THREAD

**Issue by SeedyROM** [SeedyROM/croncat-rs#79]
# Problem

Right now we only log the error reason in the `~/.croncatd/logs`, what we really want is to pipe the tracing messages from warn and error into that same log file as well.

# Ideas

- https://docs.rs/tracing-appender/latest/tracing_appender/
- https://github.com/tokio-rs/tracing/issues/971
- https://docs.rs/tracing-subscriber/latest/tracing_subscriber/layer/

**Comment by TrevorJTClarke** [comment]
@SeedyROM I am hoping for a split actually!
Logs for info/warn in 1 file, errors in another turned on by debug flag

**Comment by SeedyROM** [comment]
@TrevorJTClarke So I was thinking we have the debug flag set it shows the traceback in the terminal itself.

How about we keep that, but also always store a info/warn log and an error log. (eg. `uni-5.log` and `uni-5.error.log`).

*Using the log rotation from that crate puts the current date at the end like this `uni-5.log.2022.10.20`*
