### ISSUE TITLE
[Blocked] Agent gets tasks with rules and can execute them

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#82]
Actually, this is waiting on https://github.com/CronCats/cw-croncat/issues/160

---

Currently the agent is getting tasks and executing them using `proxy_call`.

The tasks with rules are different in that the agent will determine off-chain whether the rules evaluate to true. Once they do, the agent will call `proxy_call_with_rules` and provide the task hash. From there, the contract doesn't simply trust the agent, but does the necessary checks to ensure the rules are indeed evaluating to true, then it executes it.

**Comment by Buckram123** [comment]
Hey, can you give a more details what's missing?
From what I see, we have a flag for the "go" command, called "with_rules"(with shortname "r")
https://github.com/CronCats/croncat-rs/blob/feacce1f2b0b94f6f618421f31e9f1b425486b9d/croncatd/src/opts.rs#L95-L96

When it's on it will create this tokio task: https://github.com/CronCats/croncat-rs/blob/feacce1f2b0b94f6f618421f31e9f1b425486b9d/croncat/src/streams/tasks.rs#L73

**Comment by mikedotexe** [comment]
My mistake! Closing
