### ISSUE TITLE
Introduce threshold where agent automatically withdraws some balance

### ISSUE THREAD

**Issue by mikedotexe** [SeedyROM/croncat-rs#84]
Great news, last night I let the agent and new contract run for a couple hours. At the end of the night I noticed there were error messages like this:

<img width="1060" alt="Screen Shot 2022-10-22 at 10 19 25 AM" src="https://user-images.githubusercontent.com/1042667/197353740-15cddf08-484e-49a2-b245-b0b20ce79554.png">

I took a look in the contract and the agent, then ran this command to see the agent info so I could copy the address:

    cat ~/.croncatd/agents.json

After copying, threw it into this command to query the balance on testnet:

    junod q bank balances juno1hntaw5cgvxz0gftpd9gec876n0l6az20clrred --chain-id uni-5 --node https://rpc.uni.juno.deuslabs.fi:443 -o json | jq

and that returns:

```json
{
  "balances": [
    {
      "denom": "ujunox",
      "amount": "11366" // NOTICE THIS
    },
    {
      "denom": "uusdcx",
      "amount": "10000000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "0"
  }
}
```

So it looks like it was super successful! And ran all the way down until it could no longer afford to call `proxy_call` anymore.

---

So this ticket is to create some threshold, that when the agent falls below that, it calls the `withdraw` function on the smart contract to "top it off."

Here's an interesting wrinkle here… Currently we have the configuration in the YAML files per network, like `config.uni-5.yaml` for Juno's testnet. That's a good place to store items specific to the network, but it's arguable that it might not be the best place to store global configurations.

From my experience with starrybot, we took a look at a few networks/zones/blockchains on Cosmos and saw that they seem to use micro. Put another way, I didn't see a variation, where Stargaze used giga, Juno used micro, Regen used another one, etc.

So I'd say it's reasonable to take two approaches:
1. Just store the threshold, like 3_000_000 (3 NATIVE tokens) in the existing config files we have per network, in case some networks pop up in the future that don't have six zeroes.
2. Create a global config that stores the threshold for all networks.

Whichever approach is up to your discretion.

There should likely be a second setting that's "how much to withdraw" when you fall below that threshold.

Example:
```
THRESHOLD=2000000 # 2 native tokens, note the six zeroes
AUTO_WITHDRAW_BELOW_THRESHOLD=6000000 # 6 native tokens
```

Since this will happen infrequently, it doesn't seem like it's necessary to ping the RPC for balances on every block or poll. I think there's a nice balance between keeping the threshold level somewhat reasonably high, and then having some logic that checks every 10 blocks or 50 blocks or whatever. That's part of the fun of this video game, I mean ticket.

**Comment by TrevorJTClarke** [comment]
NOTE: See #85 for context as well

**Comment by mikedotexe** [comment]
This part of the draft PR may be a helpful boost:
https://github.com/CronCats/croncat-rs/pull/87/files#diff-f362c92d4773ae4710d598aa64ab45583d695d42dc9aa2aa2a0a9982cce159c1R60-R97

**Comment by TrevorJTClarke** [comment]
As part of our discussion today, see logic notes:

Withdraw:
- [ ] Check if threshold is met
- [ ] Check if reward balance available
- [ ] withdraw
- [ ] if no reward available && threshold or lower, then stop agent
