### ISSUE TITLE
Stop polling & ws process if funds are below threshold

### ISSUE THREAD

**Issue by TrevorJTClarke** [SeedyROM/croncat-rs#85]
Looks like my agent ran out of funds to process any tasks, in the previous agent, it would check if any rewards and withdraw them (see other issue for this) in this case, if there are literally no other funds the agent should stop polling & ws.

Process/Logic:
* Check agent balance
* Check if any rewards & withdraw if balance too low (within 1-2 juno)
* Check if balance is equal or below the configured threshold (i used to set it at 1.5 juno, so it never got too low)
* If no available balance above threshold, stop process so the uptime logic will stop and force an alert to the agent owner.

Default threshold should be `0.1 juno` or "enough to make 4 txns fees"

**Comment by mikedotexe** [comment]
.1 JUNO seems pretty low, I might suggest a whole JUNO, but not strongly held
