### ISSUE TITLE
Add chain-id to generate-mnemonic command

### ISSUE THREAD

**Issue by TrevorJTClarke** [SeedyROM/croncat-rs#90]
Currently theres no way to specify account creation for accounts other than `juno` [see here](https://github.com/CronCats/croncat-rs/blob/main/croncat/src/store/agent.rs#L142).

Need to add `chain-id` so the bech32 account generates for the right network.

**Comment by mikedotexe** [comment]
Interesting. Feels like the juno address is derivable from the both the private key and the seed phrase stored in the `agents.json` file.

If I were an end user wanting to run an agent, I might prefer to have one key that works across various networks, meaning it's funded on Stargaze, Osmosis, and Juno, but it's the same key.

When someone runs the `go` command, they're already forced to add the `--chain-id` flag, which opens the proper network YAML file, which contains the `prefix` key. From my work in starrybot, I remember this is enough to encode the proper Bech32 address.

Not trying to muddy the water with another option, just thinking that whatever approach we take, it's going to change how the agent interacts with `~/.croncatd/agents.json`, so work will have to be done there. At the end of the day, the thoughts I'm mentioning simply mean that a prospective agent has to run the `generate-mnemonic` command once.

And if they happen to say, `cargo run go --chain-id elgafar-1` (for Stargaze's testnet) but forgot to send funds there, we can easily derive what address they need to send to and spit out instructions on the terminal.
